# Generated by Django 2.1.3 on 2019-03-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='')),
                ('max_hash_length', models.IntegerField(default=24)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('num_links', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'record edit',
                'verbose_name_plural': 'records edit',
                'db_table': 'records',
            },
        ),
    ]
