# Generated by Django 2.1.3 on 2019-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uakari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='file',
        ),
        migrations.AddField(
            model_name='record',
            name='initial_file',
            field=models.FileField(default='none', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='record',
            name='result_file',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AlterModelTable(
            name='record',
            table='Records',
        ),
    ]
