# Generated by Django 2.1.3 on 2019-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uakari', '0002_auto_20190405_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='initial_file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='result_file',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, choices=[('Q', 'in queue'), ('ST', 'started'), ('SC', 'success'), ('F', 'failed')], max_length=64),
        ),
    ]
