# Generated by Django 2.1.3 on 2019-04-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uakari', '0003_auto_20190409_1901'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table=None,
        ),
    ]
